<parameters>
<communication>
 <receive_servers_each>14400</receive_servers_each>
 <receive_nodes_each>120</receive_nodes_each>
 <receive_nodes_default_each>180</receive_nodes_default_each>
 <transmit_node_default_each>180</transmit_node_default_each>
 <receive_jobs_each>120</receive_jobs_each>
 <receive_jobs_default_each>120</receive_jobs_default_each>
 <receive_channels_each>120</receive_channels_each>
 <receive_channels_default_each>180</receive_channels_default_each>
 <receive_chat_each>45</receive_chat_each>
</communication>
</parameters>
