<parameters>
<communication>
 <receive_servers_each>14400</receive_servers_each>
 <receive_nodes_each>120</receive_nodes_each>
 <transmit_node_each>180</transmit_node_each>
 <receive_jobs_each>120</receive_jobs_each>
 <transmit_jobs_each>120</transmit_jobs_each>
 <receive_channels_each>120</receive_channels_each>
 <transmit_channels_each>120</transmit_channels_each>
 <receive_chat_each>45</receive_chat_each>
 <purge_server_after_failures>30</purge_server_after_failures>
</communication>
</parameters>
