rm ../../bin/*.log
rm ../../bin/*.ppu
rm ../../bin/*.php
rm ../../bin/*.html
rm ../../bin/*.ini
rm ../../bin/*.db
rm ../../bin/*.or
rm ../../bin/*.res
rm ../../bin/*.o
rm ../../bin/*.compiled
rm ../../bin/online.*
rm ../../bin/logs/*.log
rm ../../bin/*.db
rm ../../bin/locks/*.lock
rm ../../bin/plugins/lib/*.ppu
rm ../../bin/plugins/lib/*.o
rm ../../bin/plugins/lib/*.RES
rm ../../bin/plugins/lib/*.res
rm ../../bin/plugins/lib/*.compiled
rm ../../bin/plugins/lib/*.or
